### ISSUE TITLE
IPv4Network.address_exclude does not work with /32

### ISSUE THREAD

**Issue by tarkatronic** [phihag/ipaddress#25]
This example works, attempting to exclude a /31:
```
>>> from __future__ import unicode_literals
>>> from ipaddress import ip_network
>>> n = ip_network('10.0.0.0/24')
>>> n2 = ip_network('10.0.0.2/31')
>>> ns = list(n.address_exclude(n2))
>>> ns
[IPv4Network(u'10.0.0.128/25'), IPv4Network(u'10.0.0.64/26'), IPv4Network(u'10.0.0.32/27'), IPv4Network(u'10.0.0.16/28'), IPv4Network(u'10.0.0.8/29'), IPv4Network(u'10.0.0.4/30'), IPv4Network(u'10.0.0.0/31')]
```
However, if I change `n2` to be a /32, I get...
```
>>> n2 = ip_network('10.0.0.2/32')
>>> ns = list(n.address_exclude(n2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwilhelm/.virtualenvs/thor_api/lib/python2.7/site-packages/ipaddress.py", line 921, in address_exclude
    s1, s2 = s2.subnets()
ValueError: need more than 1 value to unpack
>>>
```

It appears that this same bug exists upstream as well in Python 3.5.1.

**Comment by tarkatronic** [comment]
https://bugs.python.org/issue26457

**Comment by phihag** [comment]
I resynced with upstream and believe this to be fixed.
